### ISSUE TITLE
UglifyJS3 & harmony

### ISSUE THREAD

**Issue by xyzdata** [gildata/UglifyJS-3#1]
# UglifyJS3 & harmony

https://github.com/mishoo/UglifyJS2/tree/harmony

**Comment by xyzdata** [comment]
# λ


```css

.content h1:before {
    content: "λ";
    border: 1px solid #e44;
    padding: 0 7px;
    -moz-border-radius: 15px;
    -webkit-border-radius: 15px;
    -o-border-radius: 15px;
    -khtml-border-radius: 15px;
    -ms-border-radius: 15px;
    border-radius: 15px;
    margin-right: 0.5em;
    color: #e44;
}

```

http://lisperator.net/
